### ISSUE TITLE
log

### ISSUE THREAD

**Issue by wadayamada** [wadayamada/20241111-isucon10-final#1]
初回実行
```
Count: 
  admin-answer-clarification: 48
  admin-get-clarification: 48
  admin-get-clarifications: 92
  audience-get-dashboard: 11242
  create-team: 10
  enqueue-benchmark: 339
  finish-benchmark: 338
  get-clarification: 48
  get-dashboard: 497
  join-member: 20
  list-notifications: 3988
  post-clarification: 48
  resolve-clarification: 40
(4774 * 1.0) + 1124 - 0(err: 0, timeout: 6)
Pass: true / score: 5898 (5898 - 0)
```
